seu_nome=str(input("Digite seu nome: "))
email=str(input("Digite seu e-mail: "))
endereco=str(input("Digite seu endereço: "))
telefone=str(input("Digite seu telefone: "))
idade=str(input("Digite sua idade: "))
salario=str(input("Digite seu salário: "))
sexo=str(input("Digite seu sexo: "))

print ("Nome-", seu_nome)
print ("E-mail-", email)
print ("Endereço-", endereco)
print ("Telefone-", telefone)
print ("Idade-", idade)
print ("Salário-", salario)
print ("Sexo-", sexo)